on:
  push:
    branches: [main]

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps  # FTPSを使用(サーバーが対応している場合)
        server-dir: aa8692919.stars.ne.jp/public_html/todo_list/ #実際のパスに変更
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
        timeout: 300000  # 5分
